apiVersion: v1
kind: ConfigMap
metadata:
  name: release-nginx-ingress
  namespace: 
  labels:
    app.kubernetes.io/name: release-nginx-ingress
    helm.sh/chart: nginx-ingress-0.4.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: release
data:
