
apiVersion: v1
kind: Service
metadata:
  name: release-nginx-ingress
  namespace: 
  labels:
    app.kubernetes.io/name: release-nginx-ingress
    helm.sh/chart: nginx-ingress-0.4.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: release
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app:  release-nginx-ingress
