apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bitcoin-operator
  template:
    metadata:
      labels:
        name: bitcoin-operator
    spec:
      serviceAccountName: bitcoin-operator
      containers:
        - name: bitcoin-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - bitcoin-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bitcoin-operator"
